# Generated by Django 3.1.4 on 2020-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_id', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=50)),
                ('status_id', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Super Market Records',
            },
        ),
    ]
