# Generated by Django 3.1.4 on 2020-12-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='records',
            options={'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='records',
            name='car_model',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='records',
            name='machine_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='records',
            name='mfg_div',
            field=models.CharField(default='', max_length=50),
        ),
    ]
